version: '3.8'

services:
  api:
    build:
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GROK_API_KEY=${GROK_API_KEY}
      - UPSTASH_VECTOR_REST_URL=${UPSTASH_VECTOR_REST_URL}
      - UPSTASH_VECTOR_REST_TOKEN=${UPSTASH_VECTOR_REST_TOKEN}
    volumes:
      -./configs:/app/configs
      -./data:/app/data
    healthcheck:
      test:
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    image: node:18-alpine
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      -./ui:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api